### ISSUE TITLE
Add badge color properties to Tab

### ISSUE THREAD

**Issue by anderssonjohan** [Lundalogik/lime-elements#1005]
## New feature motivation

Today you can choose to sprinkle colors of your different tabs but you can't give the badges different colors.
If I for example want to highlight that there are zero signed documents with a red colored badge I could make that tab pop by using a red badge color. 

Example look:

<img width="520" alt="Screenshot 2020-10-29 at 12 48 17" src="https://user-images.githubusercontent.com/435885/97564589-16767800-19e5-11eb-8593-db9e01a4a28c.png">

## New feature description

The properties `Tab.badgeTextColor` and `Tab.badgeBackgroundColor` allows customization of the  similar to the already existing `Tab.iconColor` that allows highlighting the tab using different colors. This allows access to controlling the properties on the badge inside the Tab similar to when using a badge directly, which can be controlled using a style like:

```css
.badge {
    --badge-background-color: var(--lime-blue);
    --badge-text-color: white;
}
```

## New feature implementation

* Add the property `Tab.badgeTextColor`
* Add the property `Tab.badgeBackgroundColor`

**Comment by Kiarokh** [comment]
Badges on tab bars should _**all**_ communicate the _same thing_. Adding individual colors to them will just mess up the UI and will certainly confuse the users. So this is not a good idea. 

If you want to change the badge color for all, it is already possible:

```scss
limel-tab-panel { // or whatever component that includes `limel-tab-bar`
    --badge-background-color: var(--lime-blue);
    --badge-text-color: white;
}
```
