### ISSUE TITLE
Input field: helper text shows up correctly for the component itself, but not when it is used in `limel-form`

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#2617]
## Current behavior
<img width="1109" alt="image" src="https://github.com/Lundalogik/lime-elements/assets/35954987/be8052b6-6c13-46ba-8376-c33403563a3c">
Even though the field is `focus`ed, the helperText is not displayed. 

This seems to be due to the specificity of the CSS:

<img width="427" alt="image" src="https://github.com/Lundalogik/lime-elements/assets/35954987/f5cdb724-8c26-4744-8bd9-d4bacb14f8b6">

This happens because In the first block in this mixin SCSS code:
```scss
@mixin hide-helper-line-when-not-needed($component-tag) {
    // This is when:
    // - the component is not focused, or
    // - an interactive element within the component is not focused, or
    // - the component is valid

    :host(#{$component-tag}:focus),
    :host(#{$component-tag}:focus-visible),
    :host(#{$component-tag}:focus-within),
    :host(#{$component-tag}[invalid]) {
        --limel-h-l-grid-template-rows-transition-speed: 0.46s;
        --limel-h-l-grid-template-rows: 1fr;
    }

    :host(#{$component-tag}),
    :host(#{$component-tag}[invalid='false']) {
        --limel-h-l-grid-template-rows-transition-speed: 0.3s;
        --limel-h-l-grid-template-rows: 0fr;
    }
}
```

`:host(#{$component-tag}[invalid]) ` is supposed to target the web-compnents that have an invalid tag on them. The first lines are supposed to target the web-components that have received focus. 

However, if the component in the DOM gets `invalid="false"`, the CSS rules in the second block will override the first block. If I remove `:host(#{$component-tag}[invalid='false'])` from the second block, the `:host(#{$component-tag}[invalid]) ` from the first block will become true, even for those web-components that have the `invalid='false'` tag on them.

I'm trying to refactor the CSS and make sure that the styles works correctly. 

⚠️ Important to note that when the components are invalid, they can sometimes get only an `invalid` tag, and sometimes get an `invalid="true"` tag (e.g. in `limel-form`.
